---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11  # or specific tag
      hooks:
          - id: yamlfmt
            args: [--width, '150']
