---
name: Validate Pull Request
on:
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Lint YAML files
              run: yamllint transformations/ --format=github

