name: Deploy Transformations

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy-tranformations:
    runs-on: ubuntu-latest
    name: Transformations
    steps:
      - uses: actions/checkout@v2
      
      - name: Transformations Deploy step
        uses: transformations-cli@main
        id: deploy-tranformations
        env:
          API_KEY: ${{secrets.EXAMPLE_API_KEY}}
        with:
          path: apikey_examples
          api-key: ${{secrets.EXAMPLE_API_KEY}}
          cdf-project-name: jetfiretest # to suppress python SDK warning (not required for API keys).
      - name: Transformations Deploy step with OIDC
        uses: transformations-cli@main
        id: deploy-tranformations-2
        env:
          TOKEN_URL: https://login.microsoftonline.com/b86328db-09aa-4f0e-9a03-0136f604d20a/oauth2/v2.0/token
          SCOPES: https://westeurope-1.cognitedata.com/.default
          CDF_PROJECT_NAME: jetfiretest-westeurope1
          CLIENT_ID: ${{secrets.EXTRACTORS_CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.EXTRACTORS_CLIENT_SECRET}}
        with:
          path: oidc_examples
          client-id: ${{secrets.EXTRACTORS_CLIENT_ID}}
          client-secret: ${{secrets.EXTRACTORS_CLIENT_SECRET}}
          cdf-project-name: jetfiretest-westeurope1
          token-url: https://login.microsoftonline.com/b86328db-09aa-4f0e-9a03-0136f604d20a/oauth2/v2.0/token
          scopes: https://westeurope-1.cognitedata.com/.default
          cluster: westeurope-1

