name: Deploy transformations

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        name: Deploy transformations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Extract branch name
              shell: bash
              # If branch name has hyphens, replace with underscores
              run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/} | sed -e s/-/_/g)"
              id: extract_name

            - name: Resolve secrets
              shell: bash
              env:
                  BRANCH: ${{ steps.extract_name.outputs.name }}
              run: |
                  echo "##[set-output name=transformations_client_secret;]$(echo transformations_client_secret_${BRANCH})"
                  echo "##[set-output name=cognite_client_secret;]$(echo cognite_client_secret_${BRANCH})"
              id: extract_secrets

            - name: Deploy transformations
              uses: cognitedata/transformations-cli@main
                if: false  # Remove this line or this wont run! ;)
              env:
                  # Credentials to be used when running your transformations,
                  # as referenced in your manifests:
                  COGNITE_CLIENT_ID: <cognite-client-id>
                  COGNITE_CLIENT_SECRET: ${{ secrets[steps.extract_secrets.outputs.cognite_client_secret] }}
              with:
                  path: transformations
                  client-id: <cognite-client-id>
                  client-secret: ${{ secrets[steps.extract_secrets.outputs.transformations_client_secret] }}
                  cdf-project-name: <my-cdf-project>
                  token-url: https://login.microsoftonline.com/<my-azure-tenant-id>/oauth2/v2.0/token
                  scopes: https://<my-cluster>.cognitedata.com/.default
                  # If you are not using the main cluster (europe-west1-1), specify it here:
                  # cluster: greenfield
                  # Audience (for non AAD idps)
                  #audience: <audience>

